<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Предобработка-данных" data-toc-modified-id="Предобработка-данных-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Предобработка данных</a></span></li><li><span><a href="#Разделение-данных" data-toc-modified-id="Разделение-данных-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Разделение данных</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

### Предобработка данных

Начнём работу с данными с импорта библиотек.

In [1]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
path_data = "/datasets/insurance.csv"

if os.path.exists(path_data):
    data = pd.read_csv(path_data)
else:
    print('Что-то не так!')

Рассмотрим эти данные и проведём предобработку, если таковая потребуется.

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
data['Пол'].unique()

array([1, 0])

In [5]:
data['Возраст'].unique()

array([41., 46., 29., 21., 28., 43., 39., 25., 36., 32., 38., 23., 40.,
       34., 26., 42., 27., 33., 47., 30., 19., 31., 22., 20., 24., 18.,
       37., 48., 45., 44., 52., 49., 35., 56., 65., 55., 57., 54., 50.,
       53., 51., 58., 59., 60., 61., 62.])

In [6]:
data['Зарплата'].unique()

array([49600., 38000., 21000., 41700., 26100., 41000., 39700., 38600.,
       49700., 51700., 36600., 29300., 39500., 55000., 43700., 23300.,
       48900., 33200., 36900., 43500., 36100., 26600., 48700., 40400.,
       38400., 34600., 34800., 36800., 42200., 46300., 30300., 51000.,
       28100., 64800., 30400., 45300., 38300., 49500., 19400., 40200.,
       31700., 69200., 33100., 31600., 34500., 38700., 39600., 42400.,
       34900., 30500., 24200., 49900., 14300., 47000., 44800., 43800.,
       42700., 35400., 57200., 29600., 37400., 48100., 33700., 61800.,
       39400., 15600., 52600., 37600., 52500., 32700., 51600., 60900.,
       41800., 47400., 26500., 45900., 35700., 34300., 26700., 25700.,
       33300., 31100., 31500., 42100., 37300., 42500., 27300., 46800.,
       33500., 44300., 41600., 53900., 40100., 44600., 45000., 32000.,
       38200., 33000., 38500., 51800., 33800., 46400., 43200., 31800.,
       50200., 35100., 30700., 45800., 49300., 42800., 33600., 50300.,
      

In [7]:
data['Члены семьи'].unique()

array([1, 0, 2, 4, 3, 5, 6])

In [8]:
data['Страховые выплаты'].unique()

array([0, 1, 2, 3, 5, 4])

In [9]:
data.isna().sum()

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

С данными всё в порядке - нет неявных дубликатов и пропусков. Единственное, что следует изменить - тип данных в колонках `Возраст` и `Зарплата` с `float`на `integer`.

In [10]:
data[['Зарплата', 'Возраст']] = data[['Зарплата', 'Возраст']].astype('int')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Пол                5000 non-null   int64
 1   Возраст            5000 non-null   int64
 2   Зарплата           5000 non-null   int64
 3   Члены семьи        5000 non-null   int64
 4   Страховые выплаты  5000 non-null   int64
dtypes: int64(5)
memory usage: 195.4 KB


Предобработка данных завершена, теперь нужно разделить данные

### Разделение данных

In [12]:
features = data.drop(['Страховые выплаты'], axis = 1)
target = data['Страховые выплаты']

In [13]:
train_features, test_features, train_target, test_target = train_test_split(features, target, test_size = 0.25, random_state = 12345)

In [14]:
print(train_features.shape, test_features.shape, train_target.shape, test_target.shape)

(3750, 4) (1250, 4) (3750,) (1250,)


**Вывод**

Была произведена предобработка данных и были успешно разделены данные.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Если умножить признаки на обратную матрицу 

**Обоснование:** 

Подставим в формулу вектора предсказаний формулу обучений:

$$
a = X(X^T X)^{-1} X^T y
$$

Умножаем матрицу признаков X на матрицу P:

$$
XP((XP)^T XP)^{-1} (XP)^T y =
$$

Используем свойство произведения транспонированных матриц: `(AB)^T = B^T A^T`

$$
= XP((P^T X^T XP)^{-1} P^T X^T y = 
$$

Раскрываем скобки.

$$
= XP(P^T)^{-1} (X^T X)^{-1} P^{-1} P^T X^T y =
$$

Группируем матрицы с обратными им.

$$
= XP P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y =
$$

Получаем конечный результат.

$$
= X (X^T X)^{-1} X^T y
$$

Видим, что матрица $P$ в результате преобразований исчезла из уравнения, а вектор целевого признака $y$ зависит от наших результатов регрессии.

## Алгоритм преобразования

**Алгоритм**

Умножить матрицу, содержащую признаки, на любую обратимую матрицу.

**Обоснование**

Учитывая суть задания - преобразовать данные клиента без потери качества модели машинного обучения, можно применить данный алгоритм, так как мы доказали, что умножение этих признаков на случайную обратимую матрицу не ухудшает качество линейной регрессии.

## Проверка алгоритма

Обучим модель на наших данных.

In [15]:
model = LinearRegression().fit(train_features, train_target)
predictions = model.predict(test_features)
print("R2-score модели равен", r2_score(test_target, predictions))

R2-score модели равен 0.4352275684083322


In [16]:
random_matrix = np.random.normal(size = [4, 4])

det = np.linalg.det(random_matrix)
print(det)

2.2981741019490403


Теперь умножим матрицу признаков на случайную матрицу.

In [17]:
features_new = [[]]

while det == 0:
    print('Определитель матрицы равен 0, матрица является необратимой!')
    random_matrix = np.random.normal(size = [4, 4])
    det = np.linalg.det(random_matrix)
    

features_new = features @ random_matrix

features_new

0             1             2             3
0      9943.917436 -45977.923433 -35675.769221  12684.053690
1      7605.727518 -35210.018887 -27342.692869   9728.190090
2      4200.091036 -19453.798500 -15112.410283   5377.678062
3      8371.865695 -38668.931890 -29985.809534  10658.693806
4      5226.964396 -24187.423763 -18776.605876   6676.789055
...            ...           ...           ...           ...
4995   7158.542180 -33095.548470 -25678.308973   9131.363500
4996  10513.528288 -48581.380056 -37683.938325  13396.655826
4997   6803.331421 -31433.547258 -24379.232655   8667.119135
4998   6559.928240 -30320.919199 -23518.416300   8360.959518
4999   8144.375523 -37641.147772 -29198.635753  10378.992496

[5000 rows x 4 columns]

Признаки отличаются от тех, что находятся в исходных данных. Теперь обучим модель на новых данных и сравним R2-score старой и новой моделей.

In [18]:
train_features, test_features, train_target, test_target = train_test_split(features_new, target, test_size = 0.25, random_state = 12345)

In [19]:
print(train_features.shape, test_features.shape, train_target.shape, test_target.shape)

(3750, 4) (1250, 4) (3750,) (1250,)


In [20]:
model = LinearRegression().fit(train_features, train_target)
predictions = model.predict(test_features)
print("R2-score модели равен", r2_score(test_target, predictions))

R2-score модели равен 0.43522756840831356


Видно, что показатель R2 для старой и новой моделей одинаков. Умножение на случайную матрицу никак не повлияло на точность модели.

## Вывод

В результате выполнения данного проекта был проведён ряд действий.

* Загружены и подготовлены данные. 
* Был получен ответ на вопрос об умножении признаков на обратимую матрицу.
* Был предложен алгоритм преобразования.
* Был проверен предложенный алгоритм.